version: '{build}'
os: Visual Studio 2015
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: aKioN0ffdE4bl8U2pyazFCwZeMIA7hcO8cFCRujFjhwJuvW93AOpPj5WPc+WxdF/
install:
- ps: >-
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))

    $env:Path = "C:\Program Files (x86)\MSBuild\14.0\Bin;" + [Environment]::GetEnvironmentVariables("Machine")["Path"] + ";" + [Environment]::GetEnvironmentVariables("User")["Path"]

    dnvm install 1.0.0-rc1-update2
before_build:
- ps: dnu restore
build:
  verbosity: minimal
test_script:
- ps: ./Coverage.ps1